# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_reason", models.CharField(max_length=255)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Alerts",
                "db_table": "alerts",
                "ordering": ["-alert_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("isloggedin", models.BooleanField(db_column="isLoggedin")),
            ],
            options={
                "verbose_name": "Sessions",
                "db_table": "sessions",
                "ordering": ["-access_datetime"],
            },
        ),
    ]
