# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="alerts",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="user_sessions.sessions",
            ),
        ),
        migrations.AddIndex(
            model_name="sessions",
            index=models.Index(fields=["user"], name="sessions_user_id_7acd24_idx"),
        ),
        migrations.AddIndex(
            model_name="sessions",
            index=models.Index(
                fields=["access_datetime"], name="sessions_access__0097e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessions",
            constraint=models.UniqueConstraint(
                fields=("user", "access_datetime"), name="unique_user_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessions",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access_datetime__lte", django.db.models.functions.datetime.Now())
                ),
                name="access_not_in_future",
            ),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(fields=["session"], name="alerts_session_6b4a0a_idx"),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(fields=["resolved"], name="alerts_resolve_915a53_idx"),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(
                fields=["alert_timestamp"], name="alerts_alert_t_e3b260_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alerts",
            constraint=models.UniqueConstraint(
                fields=("session", "alert_timestamp", "error_reason"),
                name="unique_alert_user_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="alerts",
            constraint=models.CheckConstraint(
                condition=models.Q(("error_reason", ""), _negated=True),
                name="alert_reason_not_empty",
            ),
        ),
    ]
