# Generated by Django 5.2.5 on 2025-10-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_add_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='sid',
        ),
    ]
