# Generated by Django 5.2.5 on 2025-09-16 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Token',
                'verbose_name_plural': 'Login Tokens',
                'db_table': 'login_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token'], name='login_token_user_id_e66ea4_idx'), models.Index(fields=['expires_at'], name='login_token_expires_133cb3_idx'), models.Index(fields=['created_at'], name='login_token_created_7a566c_idx')],
            },
        ),
    ]
