# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshops",
            fields=[
                ("workshop_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("workshop_name", models.CharField(max_length=255)),
                ("start_datetime", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("location", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zoom_link", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_flag", models.BooleanField(default=False)),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="groups.groups"
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "db_table": "workshops",
            },
        ),
        migrations.CreateModel(
            name="WorkshopAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responded", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshops.workshops",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Attendance",
                "verbose_name_plural": "Workshop Attendances",
                "db_table": "workshop_attendance",
            },
        ),
        migrations.AddIndex(
            model_name="workshops",
            index=models.Index(
                fields=["start_datetime"], name="workshops_start_d_ee3d73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workshops",
            index=models.Index(fields=["group"], name="workshops_group_i_f53249_idx"),
        ),
        migrations.AddIndex(
            model_name="workshops",
            index=models.Index(
                fields=["host_user"], name="workshops_host_us_e187e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workshopattendance",
            constraint=models.UniqueConstraint(
                fields=("workshop", "user"), name="pk_workshop_attendance"
            ),
        ),
    ]
