# Generated by Django 5.2.5 on 2025-09-14 06:20

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="groups.countrystates",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="groups.tracks",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AreasOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_desc", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Area of Interest",
                "verbose_name_plural": "Areas of Interest",
                "db_table": "areas_of_interest",
            },
        ),
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_desc_unique_field", models.TextField()),
            ],
            options={
                "verbose_name": "Background",
                "verbose_name_plural": "Backgrounds",
                "db_table": "background",
            },
        ),
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                (
                    "relationship_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("relationship_type", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Relationship Type",
                "verbose_name_plural": "Relationship Types",
                "db_table": "relationship_type",
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
                "db_table": "admin_profile",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pg_first_name", models.CharField(max_length=255)),
                ("pg_last_name", models.CharField(max_length=255)),
                ("parent_guardian_flag", models.BooleanField(default=False)),
                ("school_name", models.CharField(max_length=255)),
                ("year_lvl", models.CharField(max_length=255)),
                ("has_join_permission", models.BooleanField(default=False)),
                (
                    "interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.areasofinterest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "db_table": "student_profile",
            },
        ),
        migrations.CreateModel(
            name="SupervisorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Supervisor Profile",
                "verbose_name_plural": "Supervisor Profiles",
                "db_table": "supervisor_profile",
            },
        ),
        migrations.CreateModel(
            name="StudentInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.areasofinterest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Interest",
                "verbose_name_plural": "Student Interests",
                "db_table": "student_interest",
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.CharField(db_column="Institution", max_length=255),
                ),
                ("mentor_reason", models.CharField(max_length=255)),
                ("max_grp_cnt", models.IntegerField()),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.background",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Profile",
                "verbose_name_plural": "Mentor Profiles",
                "db_table": "mentor_profile",
            },
        ),
        migrations.CreateModel(
            name="StudentSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.relationshiptype",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentprofile",
                    ),
                ),
                (
                    "supervisor_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.supervisorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Supervisor",
                "verbose_name_plural": "Student Supervisors",
                "db_table": "student_supervisor",
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.supervisorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["track"], name="users_track_i_1a6677_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["state"], name="users_state_i_69ebd8_idx"),
        ),
        migrations.AddIndex(
            model_name="studentinterest",
            index=models.Index(fields=["user"], name="student_int_user_id_9467fc_idx"),
        ),
        migrations.AddIndex(
            model_name="studentinterest",
            index=models.Index(
                fields=["interest"], name="student_int_interes_fc51c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentinterest",
            constraint=models.UniqueConstraint(
                fields=("interest", "user"), name="pk_student_interest"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_grp_cnt__gte", 0)),
                name="mentor_max_grp_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="studentsupervisor",
            index=models.Index(
                fields=["student_user"], name="student_sup_student_0afdc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsupervisor",
            index=models.Index(
                fields=["supervisor_user"], name="student_sup_supervi_51462f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsupervisor",
            constraint=models.UniqueConstraint(
                fields=("student_user", "supervisor_user"), name="pk_student_supervisor"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsupervisor",
            constraint=models.CheckConstraint(
                condition=models.Q(("relationship_type", None), _negated=True),
                name="relationship_type_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsupervisor",
            constraint=models.CheckConstraint(
                condition=models.Q(("student_user", None), _negated=True),
                name="student_user_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsupervisor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("supervisor_user__isnull", True),
                    models.Q(
                        ("student_user", models.F("supervisor_user")), _negated=True
                    ),
                    _connector="OR",
                ),
                name="no_self_supervision",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["supervisor"], name="student_pro_supervi_0372b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["interest"], name="student_pro_interes_58353d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("pg_first_name", ""), _negated=True),
                name="student_first_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("pg_last_name", ""), _negated=True),
                name="student_last_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("school_name", ""), _negated=True),
                name="student_school_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("year_lvl__in", ["9", "10", "11", "12"])),
                name="student_year_lvl_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("has_join_permission", False),
                    ("parent_guardian_flag", True),
                    _connector="OR",
                ),
                name="permission_requires_parent_guardian",
            ),
        ),
    ]
