# Generated by Django 5.2.5 on 2025-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joinperm_responseID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
