# Generated by Django 5.2.5 on 2025-10-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail',
            options={'verbose_name': 'Send Email', 'verbose_name_plural': 'Send Emails'},
        ),
    ]
