# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("attendance_status", models.BooleanField(default=False)),
                ("rsvp_status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Event Invite",
                "verbose_name_plural": "Event Invites",
                "db_table": "event_invite",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_datetime", models.DateTimeField()),
                ("ends_datetime", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("humanitix_link", models.URLField(max_length=255)),
                ("deleted_flag", models.BooleanField(default=False)),
                (
                    "deleted_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "event_image",
                    models.CharField(
                        blank=True,
                        db_column="event_image(IMG)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventTargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Target Group",
                "verbose_name_plural": "Event Target Groups",
                "db_table": "event_target_group",
            },
        ),
        migrations.CreateModel(
            name="EventTargetRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Target Role",
                "verbose_name_plural": "Event Target Roles",
                "db_table": "event_target_role",
            },
        ),
        migrations.CreateModel(
            name="EventTargetTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Target Track",
                "verbose_name_plural": "Event Target Tracks",
                "db_table": "event_target_track",
            },
        ),
    ]
