# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("groups", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinvite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="host_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventinvite",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.events"
            ),
        ),
        migrations.AddField(
            model_name="eventtargetgroup",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.events"
            ),
        ),
        migrations.AddField(
            model_name="eventtargetgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.groups"
            ),
        ),
        migrations.AddField(
            model_name="eventtargetrole",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.events"
            ),
        ),
        migrations.AddField(
            model_name="eventtargetrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.roles"
            ),
        ),
        migrations.AddField(
            model_name="eventtargettrack",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.events"
            ),
        ),
        migrations.AddField(
            model_name="eventtargettrack",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.tracks"
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["start_datetime"], name="events_start_d_2ddaa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["host_user"], name="events_host_us_34c951_idx"),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_datetime__gt", models.F("start_datetime"))),
                name="check_event_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deleted_flag", False),
                    models.Q(
                        ("deleted_flag", True), ("deleted_datetime__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="check_deleted_flag_and_datetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_virtual", False), ("location__isnull", True), _connector="OR"
                ),
                name="check_virtual_location_null",
            ),
        ),
        migrations.AddIndex(
            model_name="eventinvite",
            index=models.Index(fields=["event"], name="event_invit_event_i_c093b3_idx"),
        ),
        migrations.AddIndex(
            model_name="eventinvite",
            index=models.Index(fields=["user"], name="event_invit_user_id_db0358_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventinvite",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attendance_status", False), ("rsvp_status", True), _connector="OR"
                ),
                name="check_attendance_requires_rsvp",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sent_datetime__lte", django.db.models.functions.datetime.Now())
                ),
                name="check_invite_sent_datetime_not_future",
            ),
        ),
        migrations.AddIndex(
            model_name="eventtargetgroup",
            index=models.Index(fields=["event"], name="event_targe_event_i_d53a84_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtargetgroup",
            index=models.Index(fields=["group"], name="event_targe_group_i_29198c_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventtargetgroup",
            constraint=models.UniqueConstraint(
                fields=("event", "group"), name="unique_event_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtargetrole",
            constraint=models.UniqueConstraint(
                fields=("event", "role"), name="unique_event_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtargettrack",
            constraint=models.UniqueConstraint(
                fields=("event", "track"), name="unique_event_track"
            ),
        ),
    ]
