# Generated by Django 4.2.23 on 2025-09-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("background", models.CharField(blank=True, max_length=120)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("UG", "University - Undergraduate"),
                            ("PG", "University - Postgraduate"),
                            ("HDR", "University - HDR"),
                            ("AC", "Academic"),
                            ("IN", "Industry"),
                        ],
                        max_length=4,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("AUS-NSW", "AUS-NSW"),
                            ("AUS-QLD", "AUS-QLD"),
                            ("AUS-VIC", "AUS-VIC"),
                            ("AUS-WA", "AUS-WA"),
                            ("BRA", "BRA"),
                            ("GLOBAL", "GLOBAL"),
                        ],
                        default="GLOBAL",
                        max_length=16,
                    ),
                ),
                ("max_groups", models.PositiveSmallIntegerField(default=1)),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="mentors", to="matching.interest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("school", models.CharField(blank=True, max_length=200)),
                ("year_level", models.PositiveSmallIntegerField()),
                ("country", models.CharField(max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("AUS-NSW", "AUS-NSW"),
                            ("AUS-QLD", "AUS-QLD"),
                            ("AUS-VIC", "AUS-VIC"),
                            ("AUS-WA", "AUS-WA"),
                            ("BRA", "BRA"),
                            ("GLOBAL", "GLOBAL"),
                        ],
                        default="GLOBAL",
                        max_length=16,
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="matching.interest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("AUS-NSW", "AUS-NSW"),
                            ("AUS-QLD", "AUS-QLD"),
                            ("AUS-VIC", "AUS-VIC"),
                            ("AUS-WA", "AUS-WA"),
                            ("BRA", "BRA"),
                            ("GLOBAL", "GLOBAL"),
                        ],
                        default="GLOBAL",
                        max_length=16,
                    ),
                ),
                ("year_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("year_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="matching.interest"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="matching.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="matching.mentor",
                    ),
                ),
            ],
            options={"unique_together": {("mentor", "weekday", "start", "end")},},
        ),
    ]
