# Generated by Django 4.2.23 on 2025-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_student_preassigned_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="preassigned_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Group Number from spreadsheet (already grouped students)",
                max_length=64,
            ),
        ),
    ]
