# Generated by Django 4.2.23 on 2025-09-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_alter_student_preassigned_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="matching.mentor",
            ),
        ),
    ]
