# Generated by Django 4.2.23 on 2025-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_studentgroup_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="supervisor_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
