# Generated by Django 5.2.5 on 2025-10-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_mentor_is_active_student_supervisor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='experience',
        ),
    ]
