# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_type", models.CharField(max_length=255, unique=True)),
                ("requires_number", models.BooleanField(default=False)),
                ("requires_expiry", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "certificate_type",
                "indexes": [
                    models.Index(
                        fields=["certificate_type"],
                        name="certificate_certifi_187256_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MentorCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issued_by", models.CharField(max_length=255)),
                ("issued_at", models.DateField()),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="certificates.certificatetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Certificate",
                "verbose_name_plural": "Mentor Certificates",
                "db_table": "mentor_certificate",
            },
        ),
    ]
