# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorcertificate",
            name="mentor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.mentorprofile"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorcertificate",
            index=models.Index(
                fields=["mentor_profile", "certificate_type"],
                name="mentor_cert_mentor__f7358b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorcertificate",
            constraint=models.UniqueConstraint(
                fields=("mentor_profile", "certificate_type", "certificate_number"),
                name="unique_certificate_per_mentor",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorcertificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gte", django.db.models.functions.datetime.Now()),
                    ("verified", False),
                    _connector="OR",
                ),
                name="cannot_verify_expired_certificate",
            ),
        ),
    ]
