# Generated by Django 5.2.5 on 2025-10-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentorcertificate',
            name='cannot_verify_expired_certificate',
        ),
    ]
