# Generated by Django 5.2.5 on 2025-10-14 12:16

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_mentorcertificate_cannot_verify_expired_certificate'),
        ('users', '0003_studentprofile_joinperm_responseid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentorcertificate',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gte', django.db.models.functions.datetime.Now()), ('verified', False), _connector='OR'), name='cannot_verify_expired_certificate'),
        ),
    ]
