# Generated by Django 5.2.5 on 2025-10-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_mentorcertificate_cannot_verify_expired_certificate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentorcertificate',
            name='cannot_verify_expired_certificate',
        ),
    ]
