# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAssignees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Task Assignees",
                "db_table": "task_assignees",
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("due_date", models.DateTimeField()),
                ("deleted_flag", models.BooleanField(default=False)),
                (
                    "task_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tasks",
                "db_table": "tasks",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_name", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("deleted_flag", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.groups"
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "db_table": "milestone",
            },
        ),
    ]
