# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignees",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.milestone",
            ),
        ),
        migrations.AddField(
            model_name="taskassignees",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tasks.tasks",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["group"], name="milestone_group_i_aa2495_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["completed"], name="milestone_complet_c0474d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["deleted_flag"], name="milestone_deleted_5a70fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=models.Index(fields=["milestone"], name="tasks_milesto_5735eb_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignees",
            index=models.Index(fields=["task"], name="task_assign_task_id_39473c_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignees",
            index=models.Index(fields=["user"], name="task_assign_user_id_504562_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignees",
            index=models.Index(
                fields=["assigned_datetime"], name="task_assign_assigne_94a93f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignees",
            index=models.Index(
                condition=models.Q(("deleted_flag", False)),
                fields=["task"],
                name="ta_active_by_task",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignees",
            index=models.Index(
                condition=models.Q(("deleted_flag", False)),
                fields=["user"],
                name="ta_active_by_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskassignees",
            constraint=models.UniqueConstraint(
                fields=("task", "user"), name="unique_task_user"
            ),
        ),
    ]
