# Generated by Django 5.2.5 on 2025-10-24 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=255)),
                ('summary', models.TextField(help_text='Brief description shown in list view')),
                ('content', models.TextField(blank=True, help_text='Full announcement content (for detail page)', null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('mentor', 'Mentors Only'), ('supervisor', 'Supervisors Only'), ('admin', 'Administrators Only')], default='all', help_text='Target audience for this announcement', max_length=20)),
                ('external_link', models.URLField(blank=True, help_text='External URL (e.g., https://example.com)', null=True)),
                ('internal_route', models.CharField(blank=True, help_text='Frontend route path (e.g., /events/123)', max_length=255, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of announcements list')),
                ('author', models.ForeignKey(help_text='User who created this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_datetime'],
                'indexes': [models.Index(fields=['audience'], name='announcemen_audienc_66d2c3_idx'), models.Index(fields=['created_datetime'], name='announcemen_created_ef13d4_idx'), models.Index(fields=['is_pinned'], name='announcemen_is_pinn_52ad7c_idx'), models.Index(fields=['deleted_flag'], name='announcemen_deleted_6693fc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='announcement_deleted_flag_datetime_check')],
            },
        ),
    ]
