# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.groups"
            ),
        ),
    ]
