# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="sender_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="messageattachments",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.messages"
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["group", "sent_datetime"], name="messages_group_i_a65c01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["sender_user"], name="messages_sender__199d51_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messages",
            constraint=models.UniqueConstraint(
                fields=("sender_user", "group", "sent_datetime"),
                name="unique_message_per_user_per_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="messages",
            constraint=models.CheckConstraint(
                condition=models.Q(("deleted_flag__in", [True, False])),
                name="deleted_flag_boolean",
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachments",
            index=models.Index(
                fields=["message"], name="message_att_message_2a1fa5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageattachments",
            constraint=models.UniqueConstraint(
                fields=("attachment_id", "message"),
                name="unique_attachment_per_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="messageattachments",
            constraint=models.UniqueConstraint(
                fields=("message", "attachment_filename"),
                name="unique_filename_per_message",
            ),
        ),
    ]
