# Generated by Django 5.2.5 on 2025-10-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Message Resource Link',
                'verbose_name_plural': 'Message Resource Links',
                'db_table': 'message_resources',
            },
        ),
        migrations.RemoveConstraint(
            model_name='messageattachments',
            name='unique_attachment_per_message',
        ),
        migrations.AlterField(
            model_name='messageattachments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.messages'),
        ),
        migrations.AddField(
            model_name='messageresource',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='chat.messages'),
        ),
        migrations.AddField(
            model_name='messageresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_links', to='resources.resources'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['message'], name='message_res_message_8048ce_idx'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['resource'], name='message_res_resourc_d3776f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageresource',
            unique_together={('message', 'resource')},
        ),
    ]
