# Generated by Django 5.2.5 on 2025-10-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageresource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageresource',
            options={'verbose_name': 'Message Resource', 'verbose_name_plural': 'Message Resource'},
        ),
    ]
