# Generated by Django 5.2.5 on 2025-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messageresource_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachments',
            name='attachment_id',
        ),
        migrations.AddField(
            model_name='messageattachments',
            name='attachment_url',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='messageattachments',
            constraint=models.UniqueConstraint(fields=('message', 'attachment_url'), name='unique_url_per_message'),
        ),
    ]
