# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                (
                    "creation_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tracks",
            },
        ),
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "countries",
                "indexes": [
                    models.Index(
                        fields=["country_name"], name="countries_country_6f41c3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryStates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="groups.countries",
                    ),
                ),
            ],
            options={
                "db_table": "country_states",
            },
        ),
    ]
