# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="groupmembers",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.groups"
            ),
        ),
        migrations.AddField(
            model_name="tracks",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="groups.countrystates"
            ),
        ),
        migrations.AddField(
            model_name="groups",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="groups.tracks"
            ),
        ),
        migrations.AddConstraint(
            model_name="countrystates",
            constraint=models.UniqueConstraint(
                fields=("country", "state_name"), name="unique_state_per_country"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembers",
            index=models.Index(fields=["group"], name="group_membe_group_i_d2cebc_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmembers",
            index=models.Index(fields=["user"], name="group_membe_user_id_88c209_idx"),
        ),
        migrations.AddConstraint(
            model_name="groupmembers",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="unique_group_user"
            ),
        ),
        migrations.AddIndex(
            model_name="tracks",
            index=models.Index(fields=["state"], name="tracks_state_i_8ee9cb_idx"),
        ),
        migrations.AddIndex(
            model_name="tracks",
            index=models.Index(fields=["track_name"], name="tracks_track_n_60cf86_idx"),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(fields=["track"], name="groups_track_i_093220_idx"),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(
                fields=["deleted_flag"], name="groups_deleted_f0201e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(
                fields=["creation_datetime"], name="groups_creatio_f6499a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deleted_flag", True), ("deleted_datetime__isnull", False)
                    ),
                    models.Q(
                        ("deleted_flag", False), ("deleted_datetime__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="group_deleted_flag_datetime_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.UniqueConstraint(
                fields=("track", "group_name"), name="unique_group_name_per_track"
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deleted_datetime__gte", models.F("creation_datetime")),
                    ("deleted_datetime__isnull", True),
                    _connector="OR",
                ),
                name="deleted_after_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(("group_name__regex", "^\\s*$"), _negated=True),
                name="group_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "creation_datetime__lte",
                        django.db.models.functions.datetime.Now(),
                    )
                ),
                name="group_creation_not_future",
            ),
        ),
    ]
