# Generated by Django 5.2.5 on 2025-10-10 01:01

import apps.groups.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groups",
            name="unique_group_name_per_track",
        ),
        migrations.RemoveIndex(
            model_name="groups",
            name="groups_track_i_093220_idx",
        ),
        migrations.RemoveIndex(
            model_name="groups",
            name="groups_deleted_f0201e_idx",
        ),
        migrations.AddField(
            model_name="groups",
            name="cohort_year",
            field=models.IntegerField(
                db_index=True,
                default=apps.groups.models.get_current_year,
                help_text="Group Cohort Year (e.g. 2025)",
            ),
        ),
        migrations.AddField(
            model_name="groups",
            name="group_number",
            field=models.CharField(default="UNSPECIFIED", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="groups",
            name="group_name",
            field=models.CharField(
                error_messages={"blank": "Group name cannot be blank."},
                help_text="Name of Group (must not be empty)",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9 _-]+$",
                        "Only letters, numbers, spaces, underscores, and hyphens allowed.",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(
                fields=["track", "cohort_year"], name="groups_track_i_746393_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_flag", False)),
                fields=("track", "group_name", "cohort_year"),
                name="unique_ACTIVE_group_name_per_track_cohort",
            ),
        ),
    ]
