# Generated by Django 5.2.5 on 2025-10-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_remove_groups_unique_group_name_per_track_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countries",
            name="country_name_SHORT_FORM",
            field=models.CharField(default="___", max_length=3),
        ),
    ]
