# Generated by Django 5.2.5 on 2025-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_countries_country_name_short_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrystates",
            name="state_name_SHORT_FORM",
            field=models.CharField(default="___", max_length=3),
        ),
    ]
