# Generated by Django 5.2.5 on 2025-10-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_countrystates_state_name_short_form'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groups',
            name='group_creation_not_future',
        ),
    ]
