# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Role",
                "verbose_name_plural": "Resource Roles",
                "db_table": "resource_roles",
            },
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resource_description", models.CharField(max_length=255)),
                (
                    "upload_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resources",
            },
        ),
        migrations.CreateModel(
            name="RoleAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Role Assignment History",
                "verbose_name_plural": "Role Assignment Histories",
                "db_table": "role_assignment_history",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
    ]
