# Generated by Django 5.2.5 on 2025-09-14 06:20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="uploader_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resourceroles",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.resources"
            ),
        ),
        migrations.AddField(
            model_name="roleassignmenthistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="roles",
            constraint=models.CheckConstraint(
                condition=models.Q(("role_name", ""), _negated=True),
                name="role_name_not_empty",
            ),
        ),
        migrations.AddField(
            model_name="roleassignmenthistory",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources.roles",
            ),
        ),
        migrations.AddField(
            model_name="resourceroles",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.roles"
            ),
        ),
        migrations.AddIndex(
            model_name="resources",
            index=models.Index(
                fields=["uploader_user_id"], name="resources_uploade_68f1ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resources",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deleted_datetime__isnull", True),
                    ("deleted_flag", True),
                    _connector="OR",
                ),
                name="deleted_flag_true_if_deleted_datetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="resources",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deleted_datetime__gte", models.F("upload_datetime")),
                    ("deleted_datetime__isnull", True),
                    _connector="OR",
                ),
                name="deleted_after_upload",
            ),
        ),
        migrations.AddConstraint(
            model_name="resources",
            constraint=models.CheckConstraint(
                condition=models.Q(("resource_description", ""), _negated=True),
                name="resource_description_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="resources",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("upload_datetime__lte", django.db.models.functions.datetime.Now())
                ),
                name="resource_upload_not_future",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmenthistory",
            index=models.Index(fields=["user"], name="role_assign_user_id_4edae0_idx"),
        ),
        migrations.AddIndex(
            model_name="roleassignmenthistory",
            index=models.Index(fields=["role"], name="role_assign_role_id_e11f96_idx"),
        ),
        migrations.AddConstraint(
            model_name="roleassignmenthistory",
            constraint=models.UniqueConstraint(
                fields=("user", "role", "valid_from"), name="unique_user_role_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignmenthistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_to__gte", models.F("valid_from"))),
                name="valid_to_after_valid_from",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceroles",
            index=models.Index(fields=["role"], name="resource_ro_role_id_190238_idx"),
        ),
        migrations.AddConstraint(
            model_name="resourceroles",
            constraint=models.UniqueConstraint(
                fields=("resource", "role"), name="pk_resource_role"
            ),
        ),
    ]
