# Generated by Django 5.2.5 on 2025-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.CharField(max_length=255, default='Untitled Resource'),
        ),
    ]
