# Generated by Django 5.2.5 on 2025-09-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20250927_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.CharField(max_length=255),
        ),
    ]
