# Generated by Django 5.2.5 on 2025-10-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resources_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceroles',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceroles', to='resources.resources'),
        ),
    ]
