# Generated by Django 5.2.5 on 2025-10-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_add_related_name_to_resourceroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('type_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'db_table': 'resource_types',
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcetype'),
            preserve_default=False,
        ),
    ]
