# Generated by Django 5.2.5 on 2025-10-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resourcetype_resources_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcetype'),
        ),
    ]
