# Generated by Django 5.2.5 on 2025-10-16 12:19

from django.db import migrations


def populate_resource_types(apps, schema_editor):
    """Populate ResourceType table with the 4 resource types"""
    ResourceType = apps.get_model('resources', 'ResourceType')

    resource_types = [
        {'type_name': 'document', 'type_description': 'Document resources such as PDFs, guides, and written materials'},
        {'type_name': 'guide', 'type_description': 'Step-by-step guides and tutorials'},
        {'type_name': 'video', 'type_description': 'Video recordings and presentations'},
        {'type_name': 'template', 'type_description': 'Templates and boilerplate files'},
    ]

    for resource_type in resource_types:
        ResourceType.objects.get_or_create(
            type_name=resource_type['type_name'],
            defaults={'type_description': resource_type['type_description']}
        )


def reverse_populate_resource_types(apps, schema_editor):
    """Remove the resource types if migration is reversed"""
    ResourceType = apps.get_model('resources', 'ResourceType')
    ResourceType.objects.filter(
        type_name__in=['document', 'guide', 'video', 'template']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resources_resource_type'),
    ]

    operations = [
        migrations.RunPython(populate_resource_types, reverse_populate_resource_types),
    ]
