# Generated by Django 5.2.5 on 2025-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_populate_resource_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Upload a file for this resource (stored in Azure blob storage)', null=True, upload_to='resources/%Y/%m/%d/'),
        ),
    ]
