# Generated by Django 5.2.5 on 2025-10-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_resources_uploader_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resources',
            name='resource_upload_not_future',
        ),
    ]
