# Generated by Django 5.2.5 on 2025-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_remove_resources_resource_upload_not_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_file',
            field=models.FileField(
                help_text='Upload a file for this resource (stored in Azure blob storage) - REQUIRED',
                upload_to='resources/%Y/%m/%d/',
                null=False,
                blank=False
            ),
        ),
    ]
